FROM python:3.11-slim

WORKDIR /app

RUN pip install mlflow==3.12.0

COPY mlruns/ /app/mlruns/

EXPOSE 5001

CMD ["mlflow", "server", \
     "--host", "0.0.0.0", \
     "--port", "5001", \
     "--backend-store-uri", "/app/mlruns", \
     "--allowed-hosts", "*"]